#!/bin/sh
PWD=`pwd`
if [[ $PWD == "/Users/theo/Documents/work/"* ]] # 1)
then
  EMAIL=$(git config user.email)
  if [[ $EMAIL == *"ippon"* ]] # 2)
  then
    echo "";
  else
    echo "email not configured to Work in Work directory";
    echo "run:"
    echo '   git config user.email "tlebrun@ippon.fr"'
    echo ''
    exit 1; # 3)
  fi;
fi;
