#!/bin/sh
PWD=`pwd`
if [[ $PWD == *"perso"* ]] # 1)
then
  EMAIL=$(git config user.email)
  if [[ $EMAIL == *"gmail"* ]] # 2)
  then
    echo "";
  else
    echo "email not configured to Perso in Perso directory";
    echo "run:"
    echo '   git config user.email "mib.ftw@gmail.com"'
    echo ''
    exit 1; # 3)
  fi;
fi;
